Repository Intellimixiopce/intellimixio, pull requests merged in 2022-10, with the labels that each got.

#9 removed profile stats in readme
  readme.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#7 Added sitemap for google crawler
  sitemap.xml
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#15 added blogs on functions in c programming
  blogs/function-in-c-coder-harsh.md
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#13 contributing.md generated
  CONTRIBUTING.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted

#20 Updated readme file
  assets/img/Hacktoberfest_2022_banner.jpeg
  readme.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted

#19 Create yasaswini999.md
  blogs/yasaswini999.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted

#25 fix: sendMessage Button styling
  assets/css/style.css
  index.html
Labels: bug, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#26 Front-end web development:
  blogs/Front-end Web_Development.md
  blogs/Statistics For Data Science.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#28 Basic of DBMS
  blogs/dbms.md
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#31 add a favicon to website blog
  blogs/add-favicon-in-website.md
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#32 cns fundamentals blog
  blogs/Computer networks fundamentals.md
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#33 custom code snippets
  blogs/add-custom-codesnippets-vscode.md
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#34 coursera course for free
  courser-course-free.md
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#38 DBMS_Data_Model.md
  blogs/DBMS_Data_Model.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#35 Revert "basic of statistic for data science"
  blogs/Statistics For Data Science.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted
